### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by luukskeur** [Julien-prrs/purgecss-with-woocommerce#1]
Hi @Julien-prrs,

First of all thanks for the package! I've used it for the first time now and directly notices some missing classes that I needed, so i'll leave them here in case any one is missing the same and it perhaps will be merged in the package:

```
whitelist: [
  'related',
  'button',
]
whitelistPatterns: [
  /^product-/,
  /^columns-/,
]
```

.columns is used to determine the grid for the archive and .product is used everywhere.

**Comment by Julien-prrs** [comment]
Hi @luukskeur,

Thanks for helping me improve my package, I just published the 1.0.2 that include these items. 
If you notice any other missing items let me know, then I'll add them as soon as I can ✌️.
